/* CRIAÇÃO DO BANCO*/
CREATE DATABASE LIVRARIA;


/* CONECTANDO NO BANCO LIVRARIA */
USE LIVRARIA;


/* CRIAÇÃO DA TABELA LIVROS*/ 
CREATE TABLE LIVROS(
	NOME_LIVRO VARCHAR(30),
	NOME_AUTOR VARCHAR(30),
	SEXO_AUTOR CHAR(1),
	NUMERO_PAGINAS INT(11),
	NOME_EDITORA VARCHAR(30),
	VALOR_LIVRO FLOAT(4,2),
	ESTADO_EDITORA CHAR(2),
	ANO_PUBLICACAO INT(4)
);


/* INSERINDO DADOS NA TABELA */
INSERT INTO LIVROS VALUES('CAVALEIRO REAL', 'ANA CLAUDIA', 'F', 465, 'ATLAS', 49.9, 'RJ', 2009);
INSERT INTO LIVROS VALUES('SQL PARA LEIGOS', 'JOAO NUNES', 'M', 450, 'ADDISON', 98, 'SP', 2018);
INSERT INTO LIVROS VALUES('RECEITAS CASEIRAS', 'CELIA TAVARES', 'F', 210, 'ATLAS', 45, 'RJ', 2008);
INSERT INTO LIVROS VALUES('PESSOAS EFETIVAS ', 'EDUARDO SANTOS', 'M', 390, 'BETA', 78.99, 'RJ', 2018);
INSERT INTO LIVROS VALUES('HABITOS SAUDAVEIS', 'EDUARDO SANTOS', 'M', 630, 'BETA', 150.98, 'RJ', 2019);
INSERT INTO LIVROS VALUES('A CASA MARROM', 'HERMES MACEDO', 'M', 250, 'BUBBA', 60.00, 'MG', 2016);
INSERT INTO LIVROS VALUES('ESTACIO QUERIDO', 'GERALDO FRANCISCO', 'M', 310,'INSIGNA', 100, 'ES', 2015);
INSERT INTO LIVROS VALUES('PRA SEMPRE AMIGAS', 'LEDA SILVA', 'F', 510, 'INSIGNA', 78.98, 'ES', 2011);
INSERT INTO LIVROS VALUES('COPAS INESQUECIVEIS', 'MARCO ALNCANTARA', 'M', 200,'LARSON', 130.98, 'RS', 2018);
INSERT INTO LIVROS VALUES('O PODER DA MENTE', 'CLARA MAFRA', 'F', 120, 'CONTINENTAL', 56.58,'RS', 2017);


/* QUERIES DE PESQUISA */

/* TRAZER TODOS OS DADOS */
SELECT * FROM LIVROS;

/* TRAZER O NOME DO LIVRO E NOME DA EDITORA */
SELECT NOME_LIVRO, NOME_EDITORA FROM LIVROS;

/* TRAZER O NOME DO LIVRO E A UF DOS LIVROS PUBLICADOS POR AUTORES DO SEXO MASCULINO */
SELECT NOME_LIVRO, ESTADO_EDITORA FROM LIVROS
WHERE SEXO_AUTOR = 'M';

/* TRAZER O NOME DO LIVRO E NÚMERO DE PÁGINAS DOS LIVROS PUBLICADOS POR AUTORES DO SEXO FEMININO */
SELECT NOME_LIVRO, NUMERO_PAGINAS FROM LIVROS
WHERE SEXO_AUTOR = 'F';

/* TRAZER OS VALORES DO LIVROS DAS EDITORAS DE SÃO PAULO */
SELECT VALOR_LIVRO FROM LIVROS
WHERE ESTADO_EDITORA = 'SP';

/* TRAZER OS DADOS DOS AUTORES DO SEXO MASCULINO QUE TIVERAM LIVROS PUBLICADOS POR SÃO PAULO OU RIO DE JANEIRO */
SELECT NOME_AUTOR, SEXO_AUTOR FROM LIVROS
WHERE SEXO_AUTOR = 'M' 
AND (ESTADO_EDITORA = 'SP' OR ESTADO_EDITORA = 'RJ'); 


/* QUERYES PARA TREINAR OPERADORES LÓGICOS */
USE PROJETO;

SELECT * FROM CLIENTE;

/* OR - OU */
SELECT NOME
     , SEXO
	 , ENDERECO 
  FROM CLIENTE
 WHERE SEXO = 'M' 
    OR ENDERECO LIKE '%RJ%';

	
SELECT NOME
     , SEXO
	 , ENDERECO 
  FROM CLIENTE
 WHERE SEXO = 'F' 
    OR ENDERECO LIKE '%ESTACIO%';

/* AND - E*/
SELECT NOME
	 , SEXO
	 , ENDERECO
  FROM CLIENTE
 WHERE SEXO = 'M' 
   AND ENDERECO LIKE '%RJ%';

   
SELECT NOME
	 , SEXO
	 , ENDERECO 
  FROM CLIENTE 
 WHERE SEXO = 'F'
   AND ENDERECO LIKE '%ESTACIO%';


/* FUNÇÃO COUNT */ 
SELECT COUNT(*) AS "Quantidade de registros na tabela CLIENTE" 
  FROM CLIENTE;


SELECT SEXO, COUNT(*)
  FROM CLIENTE
  GROUP BY SEXO;
  
  
  
SELECT NOME
     , SEXO
	 , ENDERECO
  FROM CLIENTE
 WHERE SEXO = 'F' 
    OR ENDERECO LIKE '%RJ%';
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  




